Revert "media: v4l2-compat-ioctl32: memset stack union in compat ioctl"
../drivers/media/v4l2-core/v4l2-compat-ioctl32.c: In function 'do_video_ioctl':
../drivers/media/v4l2-core/v4l2-compat-ioctl32.c:1018:10: error: 'karg' undeclared (first use in this function)
  memset(&karg, 0, sizeof(karg));
          ^
../drivers/media/v4l2-core/v4l2-compat-ioctl32.c:1018:10: note: each undeclared identifier is reported only once for each function it appears in

This reverts commit e29e03796016c9762a3851130f1ec1c8bfe5357f.